FROM kalilinux/kali-rolling:latest

ARG TIMEZONE

ENV TZ=${TIMEZONE}

WORKDIR /tmp
ADD init.sh /tmp/

RUN ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y kali-desktop-xfce xorg xrdp xorgxrdp
RUN sed -i 's/port=3389/port=3390/g' /etc/xrdp/xrdp.ini
